# Logging configuration
log_level: info

# Process configuration
processes:
  - name: myapp
    command: /path/to/myapp
    args: []
    working_directory: /path/to/working/dir
    environment:
      - FOO=bar
    autostart: true
    autorestart: true
    start_retries: 3
    stop_signal: SIGTERM
    stop_timeout: 10s
    restart_delay: 1s
    restart_interval: 10s
    restart_retries: 3
